# config.yaml
data_processing_params:
  documents_path: /data/01_raw/md_files
  save_csv: False
  csvdf_path: /data/02_intermediate/tables/master_table.csv
  text_files_path: /data/02_intermediate/txt_files/
  arrowdf_path: /data/02_intermediate/tables/text_df

training_params:
  context_qa: /data/01_raw/training_objects/training_contexts.json
  training_json: /data/02_intermediate/training_data/training_data.json
  training_dataset: /data/02_intermediate/training_dataset

model_tracking_params:
  tracking_json_path: /data/04_model_output/tracking.json